### ISSUE TITLE
Add automation to help check wiki statistics when a request to add a wiki is opened

### ISSUE THREAD

**Issue by Elaeagnifolia** [KevinPayravi/indie-wiki-buddy#172]
I haven't fully fleshed out this idea, but opening this as a a place to dump everything on my mind and document the concept for future consideration. This is pretty low priority, as it's more of a quality of life improvement rather than a necessity. Apologies in advance if this isn't particularly the best place to post it, as it's not directly an issue with the extension itself.

## Issue Description/Proposal

Currently when a request to add a wiki to the extension is opened as an issue/PR, it needs to be manually checked whether or not the destination wiki is a good redirect choice for the origin wiki. This tends to be things like:

* Checking Special:Statistics on both wikis to compare content pages
* Checking Special:Version on destination wiki to see if there's any egregious version lag
* Checking Special:RecentChanges on both wikis to check for recent activity
* Comparing pages across Wikis to determine whether the content on the destination wiki meets or surpasses the origin wiki content

Assuming the origin and destination wikis are MediaWiki-based, the two bullet points can easily be retrieved through the Wiki API, and a Github integration/script of some sort could then post these details into the issue request and/or PRs. This would expedite the review process by helping put that information into the issue/PR and allow for reviewers to easily filter out destination wikis that don't make the cut quantitatively.

Recent changes can also be retrieved through the API, but would need to set some parameters on how to determine a Wiki's recent activity.

## Proposed Draft Workflow

1. Issue/PR is opened with origin and destination wiki URLs specified. Script is triggered.
2. Script parses the origin and destination wiki URLs. If script fails to parse, fail with a generic message asking for a manual review.
3. Script grabs the details required through the wiki APIs. For MediaWiki:
* Special:Statistics and Special:Version through `/api.php?action=query&format=json&meta=siteinfo&siprop=general%7Cstatistics`
* Special:RecentChanges through `/api.php?action=query&format=json&list=recentchanges` (See "Other Considerations")
4. Script then posts these details into the issue/PR. Something like:
```
**Origin Wiki**: https://example.wiki/
* [Statistics](https://example.wiki/Special:Statistics): 111 Content Pages
* [Version](https://example.wiki/Special:Version): MediaWiki 1.39.0
* [Recent Changes](https://example.wiki/Special:RecentChanges): 111 recent changes in the past 90 days. The last edit was on Jan. 01, 2013.

**Destination Wiki: https://destination.wiki/**
* [Statistics](https://destination.wiki/Special:Statistics): 999 Content Pages
* [Version](https://destination.wiki/Special:Version): MediaWiki 1.39.0
* [Recent Changes](https://destination.wiki/Special:RecentChanges): 999 recent changes in the past 90 days. The last edit was on Jan. 01, 2023.
```

> **Origin Wiki**: https://example.wiki/
> * [Statistics](https://example.wiki/Special:Statistics): 111 Content Pages
> * [Version](https://example.wiki/Special:Version): MediaWiki 1.39.0
> * [Recent Changes](https://example.wiki/Special:RecentChanges): 111 recent changes in the past 90 days. The last edit was on Jan. 01, 2013.
> 
> **Destination Wiki: https://destination.wiki/**
> * [Statistics](https://destination.wiki/Special:Statistics): 999 Content Pages
> * [Version](https://destination.wiki/Special:Version): MediaWiki 1.39.0
> * [Recent Changes](https://destination.wiki/Special:RecentChanges): 999 recent changes in the past 90 days. The last edit was on Jan. 01, 2023.

### Errors
If the API details cannot be retrieved, just display a generic message asking reviewers to manually review. If *any* details to get through though, then make sure to still post those.

* **On Failure to Parse URLs**
```
Failed to parse wiki URLs! Please manually review the wikis.
```

* **On Failure to Retrieve Wiki Details (But Origin Wiki Details Present)**
```
**Origin Wiki**: https://example.wiki/
* [Statistics](https://example.wiki/Special:Statistics): 111 Content Pages
* [Version](https://example.wiki/Special:Version): MediaWiki 1.39.0
* [Recent Changes](https://example.wiki/Special:RecentChanges): 111 recent changes in the past 90 days. The last edit was on Jan. 01, 2013.

**Destination Wiki: https://destination.wiki/**
Wiki details cannot be retrieved! Please manually review the wiki.
```

## Other Considerations
* Need to explore the actual technical implementation details. To be honest, I'm fuzzy on the technologies available to make this happen and what languages and tools would be best suited to develop this.
* What parameters do we want to use specifically to determine activity through Special:RecentChanges? How many edits occurred in the past X timeframe? Checking when the last edit was? 
* Ways to efficiently identify the API endpoints, as this won't always be the same across wikis
* Need to investigate if it's possible to access this information on other types of Wikis (e.g. Dokuwiki)

**Comment by KevinPayravi** [comment]
This is a great idea. Thanks for writing it up!

For technical implementation, we can look into creating a GitHub Action for it. That'll let us easily trigger and interact with new PRs.

For figuring out the path for the API (e.g. `/w/`, `/`, `/mediawiki/`, etc.), we might just need to try each of the possible paths until one of them successfully returns.

**Comment by SnorlaxMonster** [comment]
For determining the API URL, MediaWiki wikis usually include an EditURI element in their standard HTML header that specifies the API URL (specifically, XPath `head/link[@rel="EditURI"]`).

In the rare cases where it doesn't (usually very old MediaWiki versions), you can just find any other link on the page that includes `index.php` (I found that XPath `//li[@id="t-permalink"]/a` was very reliable).

**Comment by SnorlaxMonster** [comment]
The [Python script I wrote](https://github.com/SnorlaxMonster/indie-wiki-buddy-scripts/blob/main/profilewiki.py) can grab profile data about any two wikis, including all of the properties mentioned above, as well as several others. It currently supports MediaWiki, Fextralife, DokuWiki (with caveats), and Wikidot (with even more caveats).

There's [another script](https://github.com/SnorlaxMonster/indie-wiki-buddy-scripts/blob/main/compare.py) in the same repo that specifically compares two wikis, and outputs the number of content pages, number of active users, and number of recent edits of each as a Markdown table. Any information from the profile script can easily be added, but I found those 3 to be the most relevant information.

I'm not sure how to actually integrate that as a GitHub Action that runs whenever a new issue is created. From skimming [the quickstart guide](https://docs.github.com/en/actions/quickstart), it sounds likes the repo owner would need to add it.

## Example outputs
### profile.py
```json
{
  "name": "Yugipedia",
  "base_url": "yugipedia.com",
  "full_language": "en",
  "language": "en",
  "wiki_id": "ygowiki",
  "wikifarm": null,
  "platform": "mediawiki",
  "software_version": "1.31.1",
  "protocol": "https",
  "main_page": "Yugipedia",
  "content_path": "/wiki/",
  "search_path": "/index.php",
  "icon_path": "https://ms.yugipedia.com/6/64/Favicon.ico",
  "licence_name": "Creative Commons Attribution Share Alike",
  "licence_page": "Yugipedia:Licensing",
  "content_pages": 171654,
  "active_users": 131,
  "recent_edit_count": 14949,
  "latest_edit_timestamp": "2024-02-27 08:38:31+00:00"
}
```

### compare.py
| Metric                      |   Yu-Gi-Oh! Fandom Wiki |   Yugipedia |
|:----------------------------|------------------------:|------------:|
| Content pages               |                  133034 |      171654 |
| Active users                |                     144 |         131 |
| Recent edits (last 30 days) |                    2781 |       14954 |

**Comment by Elaeagnifolia** [comment]
I did a very, very rough draft of a possible Github Action YAML. It's untested, variables need to be filled in, assumes Python script, and could probably be cleaned up overall... But it's more just to have some sort of structure if anyone wants to move this forward a bit more. 

==YAML Rundown==
The action triggers when the label is assigned and checks for `add wiki` label. Once it passes those checks, it moves to the three main steps:

1. **[PYTHON SCRIPT]** Extract the origin and destination from the issue body.

- Arguments: -i <ISSUE_BODY>
- Goal: Parse the issue body and then store the origin and destination wiki URLs into the following env variables: `ORIGIN_WIKI` and `DESTINATION_WIKI`
- Other Notes: I separated this out since a script that can extract the URLs can probably be reused for other purposes.

2. **[PYTHON SCRIPT]** Compare the two Wikis and build the post

- Arguments: -o <ORIGIN_WIKI> -d <DESTINATION_WIKI>
- Goal: [Tweak the script that Snorlax Monster made](https://github.com/SnorlaxMonster/indie-wiki-buddy-scripts/blob/main/compare.py) to accept the two arguments, and have the output stored into the env variable `POST_BODY`.
- Other Considerations: Remember to include validation checks. Failing validation checks will still create a POST_BODY to post that the issue needs to be manually reviewed. Alternatively, can extend on this and have the action label as `manual review` instead of post.

3. Given env.POST_BODY exists, it should post it to the issue.

```yaml
name: Compare Wikis in opened add_wiki issues

on:
  issues:
    types: [labeled]

env:
  SCRIPT_REPOSITORY:
  SCRIPT_DIRECTORY:
  PRECHECK_SCRIPT:
  EXTRACT_WIKIS_SCRIPT:
  WIKI_COMPARE_SCRIPT:

jobs:
  compare_wikis:
    if: contains(github.event.issue.labels.*.name, 'add wiki')
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout scripts repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SCRIPT_REPOSITORY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.SCRIPT_DIRECTORY }}

      - name: Extract wikis
        run: python ${{ env.SCRIPT_DIRECTORY }}/${{ env.EXTRACT_WIKIS_SCRIPT }} -i ${{ github.event.issue.body }}

      - name: Compare wikis
        run: python ${{env.SCRIPT_DIRECTORY }}/${{env.WIKI_COMPARE_SCRIPT }} -o {{ env.ORIGIN_WIKI }} -d ${{ env.DESTINATION_WIKI }}

      - name: Add comment
        if: ${{ env.POST_BODY != '' }}
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: ${{ env.POST_BODY }}
  ```
