### ISSUE TITLE
Strikethrough doesn't appear on Brave Search

### ISSUE THREAD

**Issue by SnorlaxMonster** [KevinPayravi/indie-wiki-buddy#488]
On most search engines, when IWB replaces a search result, the original search result is struck through and faded out to indicate it has been replaced. However, on Brave Search, it seems that while the fading is applied, the strikethrough is not. For example, I was able to reproduce it on [this search for Borreload Savage Dragon](https://search.brave.com/search?q=Borreload+Savage+Dragon).

![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/7100450/2d9965b0-05a7-4a3a-86ea-98299201f0b0)

From inspecting the page source, Brave Search seems to include the following CSS rule, which supersedes IWB's selector.
```css
.h.svelte-xz5zli.svelte-xz5zli {
  display: flex;
  flex-direction: column;
  text-decoration: none !important;
}
```
